version: 0.1.0.{build}
configuration: Release
branches:
  only:
    - master
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
cache: packages -> **\packages.config
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore src\nforum.sln
after_build:
- cmd: >-
    cd src
    cd NForum.Tests.Core
    dotnet test
build:
  project: src\nforum.sln
  publish_nuget: true
test: off
artifacts:
- path: '*.nupkg'
