version: 0.1.0.{build}
configuration: Release
branches:
  only:
    - master
  init:
  - ps: "nuget sources add -Name CMD -Source $env:nuget_source -UserName $env:nuget_user -Password $env:nuget_password"
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  environment:
    nuget_user: nugetrestore@creativeminds.dk
    nuget_password:
      secure: t7dwAMlxY0RY+Ln49o6EKg==
    nuget_source: https://ci.appveyor.com/nuget/creativeminds
cache: packages -> **\packages.config
nuget:
  account_feed: true
  project_feed: true
before_build:
  - nuget restore src\nforum.sln
after_build:
- ps: >-
    Set-Location src

    Set-Location NForum.Tests.Core

    dotnet test

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresult.xml))

build:
  project: src\nforum.sln
  publish_nuget: true
test: off
artifacts:
- path: '*.nupkg'
